---
title: Corbin's first ubild
author: CLK
email: clkling@ncsu.edu
description: maybe he will figure this out?
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
